import React, { createContext, useContext, useState, useMemo } from 'react';

const translations = {
  en: {
    loginToSeeMore: 'Log in to see more information',
    helloWorld: 'HELLO WORLD!',
    profileUpdated: 'Profile updated successfully',
    profileUpdateError: 'Error updating profile',
    autosaveError: 'Autosave error: ',
    logoutError: 'Error logging out. Please try again',
    loggingOut: 'Logging out...',
    logout: 'Log out',
    personalData: 'Personal Data',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    phone: 'Phone',
    phonePlaceholder: 'Enter your phone number',
    about: 'About',
    aboutPlaceholder: 'Tell us about yourself...',
    location: 'Location',
    locationPlaceholder: 'City, country',
    skills: 'Skills',
    skillsPlaceholder: 'e.g. React, Node.js, Python',
    website: 'Website',
    saving: 'Saving...',
    saveChanges: 'Save changes',
    'Введите корректное ФИО (минимум 3 символа)': 'Enter a valid full name (at least 3 characters)',
    'Введите телефон в формате +7 (XXX) XXX-XX-XX': 'Enter phone in format +7 (XXX) XXX-XX-XX',
    'Некорректный email': 'Invalid email',
    'Укажите местоположение': 'Specify location',
    aboutTitle: 'About Me',
    aboutText: 'I study Frontend development and create websites.',
    aboutTextEn: 'I graduated from Kuban State University with a degree in Applied Informatics (Faculty of Computer Technologies and Applied Mathematics). During my studies, I demonstrated a high level of responsibility and always completed assignments on time. I am actively developing my skills in frontend development (React, JavaScript, CSS) and learning SQL, with experience in backend technologies as well. I completed an internship at JetRuby, where I independently developed a prototype of a social network with working functionality similar to Instagram. I am also passionate about game development — I created my own game in Unity and continue to improve my skills in this area.',
    projectsTitle: 'Projects',
    loadingProjects: 'Loading projects...',
    retryAttempt: 'Retry attempt',
    tryAgain: 'Try again',
    contactsTitle: 'Contacts',
    contactsText: 'Contact me in any way convenient for you',
    allRightsReserved: 'All rights reserved.',
    profileSetupTitle: 'Profile Setup',
    skip: 'Skip',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    login: 'Log in',
    register: 'Register',
    loginTitle: 'Log in to your account',
    registerTitle: 'Create an account',
    createAccount: 'Create a new account',
    alreadyHaveAccount: 'Already have an account? Log in',
    userNotFound: 'User with this email not found',
    wrongPassword: 'Incorrect password',
    emailInUse: 'Email is already in use',
    weakPassword: 'Password must be at least 6 characters',
    invalidEmail: 'Invalid email address',
    accountExistsWithDifferentCredential: 'Account already exists with a different sign-in method',
    popupClosed: 'The authentication window was closed. Please try again',
    popupCancelled: 'The previous authentication request was not completed',
    popupBlocked: 'Popup was blocked by the browser. Please allow popups for this site',
    unauthorizedDomain: 'This domain is not authorized for Firebase. Please check your Firebase settings',
    authError: 'An authentication error occurred',
    profile: 'Profile',
    loginOrRegister: 'Log in / Register',
    openGame: 'Open Game',
  },
  ru: {
    loginToSeeMore: 'Войдите, чтобы увидеть больше информации',
    helloWorld: 'ПРИВЕТ МИР!',
    profileUpdated: 'Профиль успешно обновлен',
    profileUpdateError: 'Ошибка при обновлении профиля',
    autosaveError: 'Ошибка автосохранения: ',
    logoutError: 'Ошибка при выходе из системы. Попробуйте еще раз',
    loggingOut: 'Выход...',
    logout: 'Выйти',
    personalData: 'Личные данные',
    fullName: 'ФИО',
    fullNamePlaceholder: 'Введите ФИО полностью',
    phone: 'Телефон',
    phonePlaceholder: 'Введите телефон',
    about: 'О себе',
    aboutPlaceholder: 'Расскажите о себе...',
    location: 'Местоположение',
    locationPlaceholder: 'Город, страна',
    skills: 'Навыки',
    skillsPlaceholder: 'Например: React, Node.js, Python',
    website: 'Личный сайт',
    saving: 'Сохранение...',
    saveChanges: 'Сохранить изменения',
    'Введите корректное ФИО (минимум 3 символа)': 'Введите корректное ФИО (минимум 3 символа)',
    'Введите телефон в формате +7 (XXX) XXX-XX-XX': 'Введите телефон в формате +7 (XXX) XXX-XX-XX',
    'Некорректный email': 'Некорректный email',
    'Укажите местоположение': 'Укажите местоположение',
    aboutTitle: 'Обо мне',
    aboutText: 'Я выпускник Кубанского государственного университета по направлению «Прикладная информатика» (ФКТИПМ). В процессе обучения проявил высокую ответственность и всегда своевременно выполнял учебные задания. Активно развиваюсь в сфере frontend-разработки (React, JavaScript, CSS). Дополнительно изучаю SQL, имею опыт работы с backend-технологиями. Проходил стажировку в компании JetRuby, где реализовал прототип социальной сети с рабочим функционалом, аналогичным Instagram. Также увлекаюсь геймдевом — создал собственную игру на Unity в которую вы можете поиграть прямо сейчас.',
    projectsTitle: 'Мои проекты',
    loadingProjects: 'Загрузка проектов...',
    retryAttempt: 'Повторная попытка',
    tryAgain: 'Попробовать снова',
    contactsTitle: 'Контакты',
    contactsText: 'Свяжитесь со мной удобным для вас способом',
    allRightsReserved: 'Все права защищены.',
    profileSetupTitle: 'Настройка профиля',
    skip: 'Пропустить',
    email: 'Email',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    login: 'Войти',
    register: 'Создать аккаунт',
    loginTitle: 'Вход в аккаунт',
    registerTitle: 'Создание аккаунта',
    createAccount: 'Создать новый аккаунт',
    alreadyHaveAccount: 'Уже есть аккаунт? Войти',
    userNotFound: 'Пользователь с таким email не найден',
    wrongPassword: 'Неверный пароль',
    emailInUse: 'Пользователь с таким email уже существует',
    weakPassword: 'Пароль должен содержать минимум 6 символов',
    invalidEmail: 'Некорректный email адрес',
    accountExistsWithDifferentCredential: 'Аккаунт уже существует с другим методом входа',
    popupClosed: 'Окно авторизации было закрыто. Попробуйте еще раз',
    popupCancelled: 'Предыдущий запрос авторизации не был завершен',
    popupBlocked: 'Всплывающее окно заблокировано браузером. Пожалуйста, разрешите всплывающие окна для этого сайта',
    unauthorizedDomain: 'Этот домен не авторизован для работы с Firebase. Пожалуйста, проверьте настройки Firebase',
    authError: 'Произошла ошибка при авторизации',
    profile: 'Профиль',
    loginOrRegister: 'Войти / Регистрация',
    openGame: 'Войти в игру',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Язык по умолчанию теперь русский
  const [language, setLanguage] = useState('ru');

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language][key] || key,
    translations,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
